<?php
/**
 * Implements of hook_block_info()
 */
function ajaxlogin_block_info() {
  $block['ajaxlogin'] = array(
  	'info' => t('Ajax Login'),
    'visibility' => 0,
    'status' => 1,
    'region' => 'header',
  );
  return $block;
}

/**
 * Implements hook_block_view()
 */
function ajaxlogin_block_view($delta ='') {
  $block = array();
  if($delta == 'ajaxlogin') {
    $block = array(
    	'subject' => t('Ajax Login'),
      'content' => ajaxlogin_block_content()
    );
  }

  return $block;
}

function ajaxlogin_block_content() {
  $output = '';
  if(module_exists('dialog_user')) {
      drupal_add_library('dialog', 'dialog');
      if(!user_is_logged_in()) {
        $output = '<div id="ajax-login">' .
                  l('User login', 'user/login/nojs/', array('attributes' => array('class' => array('use-dialog', 'use-ajax')))) .
  	                 ' | ' .
  	              l('Register', 'user/register/nojs/', array('attributes' => array('class' => array('use-dialog', 'use-ajax')))).
                  '</div>';
      }
  } else {
    $output = '<div id="ajax-login">'. t("dilog_user module is not installed, please contact site administrator.") . '</div>';
  }
  return $output;
}
?>